version: '3.9'

services:
    nws:
        container_name: nws
        restart: always
        build: .
        volumes:
            - /var/data/website/nws:/app/data
            - ./templates:/app/templates